version: '3'
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.8.1
    environment:
      - xpack.apm.enabled=true
      
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm-es-server:
    container_name: apm-es-container
    image: docker.elastic.co/apm/apm-server:8.1.0
    command:
     -e -strict.perms=false
    environment:
      - setup.kibana.host=kibana:5601
    volumes:
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch

volumes:  
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local